# Generated by Django 4.0.6 on 2022-07-21 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_delete_statustype'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cascade_deleted', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.CharField(max_length=256, verbose_name='description')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='status.statustype')),
                ('workflow', models.ManyToManyField(related_name='status', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
                'db_table': 'status',
            },
        ),
    ]
