# Generated by Django 4.0.6 on 2022-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='position',
            field=models.JSONField(default={}, null=True, verbose_name='position'),
        ),
    ]
