# Generated by Django 4.0.6 on 2022-07-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_status_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='position',
        ),
    ]
