# Generated by Django 4.0.6 on 2022-07-23 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_delete_statustype'),
        ('status', '0004_remove_status_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='workflow',
        ),
        migrations.CreateModel(
            name='StatusWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'status_workflow',
            },
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflow'),
        ),
        migrations.AddField(
            model_name='statusworkflow',
            name='position',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='status',
            name='workflow',
            field=models.ManyToManyField(related_name='status', through='status.StatusWorkflow', to='workflow.workflow'),
        ),
    ]
