# Generated by Django 4.0.6 on 2022-07-24 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_statusworkflow_alter_status_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='status.statustype'),
        ),
    ]
