# Generated by Django 4.0.6 on 2022-07-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_statustype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusType',
        ),
    ]
