# Generated by Django 4.0.6 on 2022-07-21 20:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0002_status'),
        ('workflow', '0005_delete_statustype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cascade_deleted', models.BooleanField(null=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition', to='status.status')),
                ('next_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_status', to='status.status')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition', to='workflow.workflow')),
            ],
            options={
                'db_table': 'transition',
            },
        ),
    ]
