# Generated by Django 4.0.6 on 2022-07-22 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_delete_statustype'),
        ('transition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflow'),
        ),
    ]
